import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/exam_result.dart';
import '../models/weak_area.dart';

class PdfAppColors {
  static const navy = PdfColor.fromInt(0xFF1B3A5C);
  static const burgundy = PdfColor.fromInt(0xFF8B2635);
  static const success = PdfColor.fromInt(0xFF2D6A4F);
  static const warning = PdfColor.fromInt(0xFFB8860B);
  static const danger = PdfColor.fromInt(0xFF9B2C2C);
  static const text = PdfColor.fromInt(0xFF2C2C2C);
  static const textMuted = PdfColor.fromInt(0xFF6B7280);
  static const border = PdfColor.fromInt(0xFFD4CCC0);
  static const bg = PdfColor.fromInt(0xFFFAF7F2);
}

class PdfReportService {
  static Future<Uint8List> generate(
    WeakAreaAnalysis analysis,
    List<ExamResult> results,
  ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(context),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildTitle(),
          pw.SizedBox(height: 20),
          _buildSummaryRow(analysis),
          pw.SizedBox(height: 24),
          _buildDomainSection(analysis),
          pw.SizedBox(height: 24),
          _buildMissedConceptsSection(analysis),
          pw.SizedBox(height: 24),
          _buildHistoryTable(results),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(pw.Context context) {
    if (context.pageNumber == 1) return pw.SizedBox();
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.only(bottom: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfAppColors.border)),
      ),
      child: pw.Text(
        'PM&R Oral Boards — Performance Report',
        style: pw.TextStyle(
          fontSize: 10,
          color: PdfAppColors.textMuted,
        ),
      ),
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 10),
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfAppColors.border)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by PM&R Oral Boards Exam Simulator',
            style: pw.TextStyle(fontSize: 8, color: PdfAppColors.textMuted),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(fontSize: 8, color: PdfAppColors.textMuted),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildTitle() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Container(height: 2, width: 60, color: PdfAppColors.navy),
        pw.SizedBox(height: 12),
        pw.Text(
          'PM&R Oral Boards',
          style: pw.TextStyle(
            fontSize: 28,
            fontWeight: pw.FontWeight.bold,
            color: PdfAppColors.navy,
          ),
        ),
        pw.Text(
          'Performance Report',
          style: pw.TextStyle(
            fontSize: 16,
            fontStyle: pw.FontStyle.italic,
            color: PdfAppColors.textMuted,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          'Generated ${DateTime.now().toIso8601String().substring(0, 10)}',
          style: pw.TextStyle(fontSize: 10, color: PdfAppColors.textMuted),
        ),
        pw.SizedBox(height: 12),
        pw.Container(height: 1, color: PdfAppColors.border),
      ],
    );
  }

  static pw.Widget _buildSummaryRow(WeakAreaAnalysis analysis) {
    final avgPct = analysis.averageScore.round();

    return pw.Row(
      children: [
        _summaryBox('Exams Taken', '${analysis.totalExams}'),
        pw.SizedBox(width: 16),
        _summaryBox('Average Score', '$avgPct%'),
        pw.SizedBox(width: 16),
        _summaryBox(
          'Concepts Tracked',
          '${analysis.topMissedConcepts.fold<int>(0, (s, c) => s + c.totalAppearances)}',
        ),
      ],
    );
  }

  static pw.Widget _summaryBox(String label, String value) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(14),
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: PdfAppColors.border),
          borderRadius: pw.BorderRadius.circular(4),
        ),
        child: pw.Column(
          children: [
            pw.Text(
              value,
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                color: PdfAppColors.navy,
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              label,
              style: pw.TextStyle(
                fontSize: 10,
                color: PdfAppColors.textMuted,
              ),
            ),
          ],
        ),
      ),
    );
  }

  static pw.Widget _buildDomainSection(WeakAreaAnalysis analysis) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Domain Performance',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfAppColors.navy,
          ),
        ),
        pw.SizedBox(height: 12),
        ...analysis.domainSummaries.entries.map((e) {
          final d = e.value;
          final pct = d.totalConcepts > 0 ? (d.hitRate * 100).round() : 0;
          final barColor = pct >= 70
              ? PdfAppColors.success
              : (pct >= 40 ? PdfAppColors.warning : PdfAppColors.danger);

          return pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 8),
            child: pw.Row(
              children: [
                pw.SizedBox(
                  width: 140,
                  child: pw.Text(
                    'Domain ${d.domain}: ${d.domainName}',
                    style: pw.TextStyle(fontSize: 10, color: PdfAppColors.text),
                  ),
                ),
                pw.Expanded(
                  child: pw.Stack(
                    children: [
                      pw.Container(
                        height: 10,
                        decoration: pw.BoxDecoration(
                          color: const PdfColor.fromInt(0xFFF5F0E8),
                          borderRadius: pw.BorderRadius.circular(3),
                        ),
                      ),
                      pw.Container(
                        height: 10,
                        width: (pct / 100.0) * 200,
                        decoration: pw.BoxDecoration(
                          color: barColor,
                          borderRadius: pw.BorderRadius.circular(3),
                        ),
                      ),
                    ],
                  ),
                ),
                pw.SizedBox(width: 8),
                pw.Text(
                  '$pct%',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: barColor,
                  ),
                ),
              ],
            ),
          );
        }),
      ],
    );
  }

  static pw.Widget _buildMissedConceptsSection(WeakAreaAnalysis analysis) {
    if (analysis.topMissedConcepts.isEmpty) return pw.SizedBox();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Most Missed Concepts',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfAppColors.navy,
          ),
        ),
        pw.SizedBox(height: 8),
        ...analysis.topMissedConcepts.take(10).toList().asMap().entries.map((e) {
          return pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Row(
              children: [
                pw.Text(
                  '${e.key + 1}. ',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfAppColors.burgundy,
                  ),
                ),
                pw.Expanded(
                  child: pw.Text(
                    e.value.concept,
                    style: pw.TextStyle(fontSize: 10, color: PdfAppColors.text),
                  ),
                ),
                pw.Text(
                  'missed ${e.value.missCount}x',
                  style: pw.TextStyle(fontSize: 9, color: PdfAppColors.danger),
                ),
              ],
            ),
          );
        }),
      ],
    );
  }

  static pw.Widget _buildHistoryTable(List<ExamResult> results) {
    if (results.isEmpty) return pw.SizedBox();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Exam History',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfAppColors.navy,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(
            fontSize: 9,
            fontWeight: pw.FontWeight.bold,
            color: PdfAppColors.navy,
          ),
          cellStyle: pw.TextStyle(fontSize: 9, color: PdfAppColors.text),
          headerDecoration: const pw.BoxDecoration(
            color: PdfColor.fromInt(0xFFF5F0E8),
          ),
          cellPadding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
          headers: ['Case', 'Date', 'Score', 'Time', 'Red Flags'],
          data: results.take(20).map((r) {
            final min = r.timeElapsedSeconds ~/ 60;
            final sec = r.timeElapsedSeconds % 60;
            return [
              r.caseTitle,
              r.date.toIso8601String().substring(0, 10),
              '${(r.overallScore * 100).round()}%',
              '$min:${sec.toString().padLeft(2, '0')}',
              '${r.redFlagCount}',
            ];
          }).toList(),
        ),
      ],
    );
  }
}
